# Session(2):

### math and scipy Libraries
• The `math` library, a standard library of Python, provides some 
common mathematical functions;\
• the `numpy` library, a numerical calculation and expansion library of Python, is 
mainly used to handle issues such as linear algebra, random 
number generation, and Fourier Transform;\
• the `scipy` library is used to deal with issues such as statistics, optimization, 
interpolation, and bonus points.

### ceilImplementation
• The value of ceil(x) is the minimum integer greater than or equal to x. If x is an integer, the returned value is 
x

In [1]:
import math
import numpy as np
import scipy as sp

In [4]:
#Example
print(math.ceil(4.1))
print(math.ceil(4.99))

5
5


### Cos & Sin & Tan Implementation
• The cos(x) parameter is the cosine of x, where x must be a radian (math.pi/4 is a radian, indicating an angle 
of 45 degrees)\
• The tan(x) parameter returns the tangent value of x (radian)

In [5]:
pi = math.pi
print("cos= ",math.cos(pi/4))
print("tan= ",math.tan(pi/4))
print("sin= ",math.sin(pi/4))

cos=  0.7071067811865476
tan=  0.9999999999999999
sin=  0.7071067811865476


### degrees Implementation
• The degrees(x) parameter converts x from a radian to an angle.

In [7]:
pi = math.pi
print(math.degrees(pi/4))
print(math.degrees(pi))

45.0
180.0


### exp, fabs, and Factorial Implementations 
• The exp(x) parameter returns math.e, that is, the x power of 2.71828.\
• The fabs(x) parameter returns the absolute value of x.\
• The factorial(x) parameter is the factorial of x.

In [9]:
print("exp= ",math.exp(10))
print("abs= ",math.fabs(-.03))
print("factorial= ",math.factorial(3))

exp=  22026.465794806718
abs=  0.03
factorial=  6


### fsum and fmod Implementations 
• The fsum(iterable) summarizes each element in the iterator.\
• The fmod(x, y) parameter obtains the remainder of x/y. The value is a floating-point number

In [10]:
print("sum= ",math.fsum([1,2,3,4]))
print("mod= ",math.fmod(20,3))

sum=  10.0
mod=  2.0


### log and sqrt Implementations
• The log([x, base]) parameter returns the natural logarithm of x. By default, e is the base number. If the base
parameter is fixed, the logarithm of x is returned based on the given base. The calculation formula is 
log(x)/log(base).\
• The sqrt(x) parameter indicates the square root of x.

In [11]:
print("log= ",math.log(10))
print("sqrt= ",math.sqrt(25))

log=  2.302585092994046
sqrt=  5.0


### pi, pow, trunc Implementations
• The pi parameter is a numeric constant, indicating the circular constant.\
• The pow(x, y) parameter returns the x to the yth power, that is, x**y.\
• The trunc(x:Real) parameter returns the integer part of x.

In [14]:
print("pi= ",math.pi)
print("power= ",math.pow(2,5))
print("trunc= ",math.trunc(6.2547))

pi=  3.141592653589793
power=  32.0
trunc=  6


# Linear Algebra
• Linear algebra is a mathematical branch widely used in various engineering technical disciplines. 
Its concepts and conclusions can greatly simplify the derivation and expression of AI formulas. 
Linear algebra can simplify complex problems so that we can perform efficient mathematical 
operations.\
• In the context of deep learning, linear algebra is a mathematical tool that provides a technique that 
helps us to operate arrays at the same time. Data structures like vectors and matrices can store 
numbers and rules for operations such as addition, subtraction, multiplication, and division.\
• The numpy is a numerical processing module based on Python. It has powerful functions and 
advantages in processing matrix data. As linear algebra mainly processes matrices, this section is 
mainly based on the numpy. This section also uses the mathematical science library scipy to 
illustrate equation solution.

### Tensor Implementation (1) 
• Generate a two-dimensional tensor whose elements are 0 and two dimensions are 3 and 4.

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Tensor Implementation (2) 
• Generate a three-dimensional random tensor whose three dimensions are 2, 3, and 4 respectively.

In [16]:
np.random.rand(2,3,4)

array([[[0.82476667, 0.01208496, 0.18037733, 0.60815062],
        [0.891377  , 0.58915207, 0.08539225, 0.34468176],
        [0.09805372, 0.60735775, 0.43508458, 0.90543294]],

       [[0.55547414, 0.84220841, 0.99331381, 0.92010579],
        [0.12300744, 0.56283495, 0.72388799, 0.75018065],
        [0.30850388, 0.4714466 , 0.90190892, 0.34141902]]])

### Identity Matrix Implementation
• Identity matrix is a square array whose diagonal elements are all 1 and other elements are 0.

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# reshape Operation (1):

x = np.arange(12)
print(x)
print(x.shape)
print("---------------------------------------------")

#reshape Operation (2):

x = x.reshape(1,12)
print(x)
print(x.shape)
print("---------------------------------------------")
x = x.reshape(3,4)
print(x)
print(x.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
---------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(1, 12)
---------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [27]:
#Transposition Implementation (1):

x = np.arange(5).reshape(1,-1)
print(x)

x = x.T
print(x)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [30]:
#Transposition Implementation (2):

x = np.arange(12).reshape(3,4)
print(x)

print("*******************")

x = x.T
print(x)

print("---------------------------------------------------------------")

y = np.arange(24).reshape(2,3,4)
print(y)

print("*******************")

y = y.T
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*******************
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
---------------------------------------------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
*******************
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [33]:
#Transposition Implementation (3):

print(y.transpose(1,0,2))

# OR

# y = np.arange(24).reshape(3,2,4)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


### Matrix Multiplication
• To multiply the matrix A and matrix B, the column quantity of A must be equal to the row quantity of B

In [36]:
A = np.arange(6).reshape(3,2)
B = np.arange(6).reshape(2,3)
print(A)
print("-----------")
print(B)
print("-----------")
print(np.matmul(A,B))

[[0 1]
 [2 3]
 [4 5]]
-----------
[[0 1 2]
 [3 4 5]]
-----------
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


### Matrix Corresponding Operation
• Matrix corresponding operations are operations for tensors of the same shape and size. For example, `adding`, 
`subtracting`, `multiplying`, and `dividing` the elements with the same position in two tensors.

In [39]:
print("sum = \n",A+A)
print("multiplying = \n",A*A)

sum = 
 [[ 0  2]
 [ 4  6]
 [ 8 10]]
multiplying = 
 [[ 0  1]
 [ 4  9]
 [16 25]]


### Inverse Matrix Implementation
• Inverse matrix implementation is applicable only to square matrices.

In [41]:
A=np.arange(4).reshape(2,2)
print(np.linalg.inv(A))

[[-1.5  0.5]
 [ 1.   0. ]]


### Eigenvalue and Eigenvector
• Obtain the eigenvalue and eigenvector of a matrix.

In [52]:
x = np.diag((1,2,3))
print("x= \n",x)
print("-----------")
a,b = np.linalg.eig(x)
print("a= ",a)
print("-----------")
print("b= \n",b)

x= 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
-----------
a=  [1. 2. 3.]
-----------
b= 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Determinant
• Obtain the determinant of a matrix. 

In [54]:
A=np.arange(16).reshape(4,4)
print(np.linalg.det(A))

-2.9582283945787796e-30


### Linear Equation Solving
• Solving a linear equation is simple because it requires only one function (scipy.linalg.solve).\
• An example is finding the solution of the following system of non-homogeneous linear equations.

In [58]:
from scipy.linalg import solve

In [61]:
"""
(3)x1 + (1)x2 + (-2)x3 = (5)
(1)x1 + (-1)x2 + (4)x3 = (2)
(2)x1 + (0)x2 + (3)x3  = (2.5)

"""
a = np.array([[3,1,-2],[1,-1,4],[2,0,3]])
b = np.array([5,2,2.5])
x = solve(a,b)
print(x)

[ 2.  -2.  -0.5]
